# Generated by Django 4.2.1 on 2023-06-21 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portal_students_api', '0002_studentactivationotp'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('employee_id', models.CharField(max_length=50)),
                ('employee_photo', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name_plural': 'security_details',
                'db_table': 'security_details',
            },
        ),
        migrations.CreateModel(
            name='EntryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_time', models.DateTimeField(auto_now_add=True)),
                ('exit_time', models.DateTimeField(auto_now_add=True)),
                ('entry_point', models.CharField(max_length=50)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='portal_students_api.student')),
            ],
            options={
                'verbose_name_plural': 'entry_logs',
                'db_table': 'entry_logs',
            },
        ),
    ]
