# Generated by Django 4.1.7 on 2023-07-12 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portal_security_api', '0001_initial'),
        ('portal_students_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrylog',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='portal_students_api.student'),
        ),
    ]
