# Generated by Django 4.2.1 on 2023-06-23 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal_security_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('short_name', models.CharField(choices=[('security_admin', 'security_admin'), ('security', 'security')], default='', max_length=20, unique=True)),
                ('is_active', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'security_roles',
            },
        ),
        migrations.AddField(
            model_name='securitydetails',
            name='role',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='portal_security_api.roles'),
            preserve_default=False,
        ),
    ]
