# Generated by Django 4.2.1 on 2023-06-25 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_security_api', '0003_securitydetails_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityAdminActivationOtp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('otp', models.IntegerField()),
                ('is_validated', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'security_admin_activation_otp',
            },
        ),
    ]
