# Generated by Django 4.2.1 on 2023-06-25 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_security_api', '0004_securityadminactivationotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='securitydetails',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
