# Generated by Django 4.2.1 on 2023-06-10 18:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portal_schools_api', '0003_facultyschool_status'),
        ('portal_school_department_api', '0004_departmentactivationotp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=50)),
                ('national_id_number', models.CharField(max_length=9)),
                ('school_id_number', models.CharField(max_length=10)),
                ('course', models.CharField(max_length=100)),
                ('status', models.IntegerField(default=0)),
                ('department', models.ManyToManyField(to='portal_school_department_api.schoolfacultydepartment')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='portal_schools_api.facultyschool')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'student',
            },
        ),
    ]
