# Generated by Django 4.1.7 on 2023-07-12 07:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portal_schools_api', '0003_facultyschool_status'),
        ('portal_school_department_api', '0004_departmentactivationotp'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentActivationOtp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('otp', models.IntegerField()),
                ('is_validated', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'student_activation_otp',
            },
        ),
        migrations.CreateModel(
            name='StudentCourseInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=50)),
                ('course_ID', models.CharField(max_length=50)),
                ('course_description', models.CharField(max_length=255)),
                ('course_duration', models.CharField(max_length=50)),
                ('course_instructor', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'student_course',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=50)),
                ('national_id_number', models.CharField(max_length=9)),
                ('school_id_number', models.CharField(max_length=10)),
                ('status', models.IntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='portal_students_api.studentcourseinformation')),
                ('department', models.ManyToManyField(to='portal_school_department_api.schoolfacultydepartment')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='portal_schools_api.facultyschool')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'student',
            },
        ),
    ]
