# Generated by Django 4.1.7 on 2023-07-12 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_students_api', '0002_courseunits'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='units',
            field=models.ManyToManyField(related_name='students', to='portal_students_api.courseunits'),
        ),
    ]
