# Generated by Django 4.1.7 on 2023-07-17 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_students_api', '0006_alter_enrollment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='units',
            field=models.ManyToManyField(null=True, related_name='enrollments', to='portal_students_api.courseunits'),
        ),
    ]
