# Generated by Django 4.1.7 on 2023-07-19 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_students_api', '0008_studentticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentticket',
            name='ticket_code',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
