# Generated by Django 4.1.7 on 2023-07-21 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_students_api', '0009_studentticket_ticket_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='units',
            field=models.ManyToManyField(related_name='enrollments', to='portal_students_api.courseunits'),
        ),
    ]
