# Generated by Django 4.1.7 on 2023-07-25 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_students_api', '0012_studentmessaging'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmessaging',
            name='thread_id',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
