# Generated by Django 4.1.7 on 2023-07-12 07:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=20)),
                ('due_date', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Invoices',
                'db_table': 'Invoice',
            },
        ),
        migrations.CreateModel(
            name='StudentsFeePayments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateField()),
                ('payment_method', models.CharField(max_length=60)),
                ('payment_status', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'students_fee_table',
                'db_table': 'students_fee_table',
            },
        ),
        migrations.CreateModel(
            name='TransactionsMade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('hostel_fee', 'hostel_fee'), ('library_fine', 'library_fine')], max_length=50)),
                ('transaction_amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('transaction_date', models.DateField()),
                ('transacting_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Transactions',
                'db_table': 'Transactions',
            },
        ),
    ]
