# Generated by Django 4.1.7 on 2023-07-12 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portal_students_api', '0001_initial'),
        ('portal_accounts_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsfeepayments',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='portal_students_api.student'),
        ),
        migrations.AddField(
            model_name='invoicetable',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='portal_students_api.student'),
        ),
    ]
