# Generated by Django 4.2.1 on 2023-06-09 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_accounts_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='universityaccounts',
            old_name='accounts_email',
            new_name='bank_account',
        ),
        migrations.RenameField(
            model_name='universityaccounts',
            old_name='accounts_name',
            new_name='bank_name',
        ),
        migrations.RemoveField(
            model_name='universityaccounts',
            name='accounts_Id',
        ),
        migrations.RemoveField(
            model_name='universityaccounts',
            name='user',
        ),
        migrations.AddField(
            model_name='universityaccounts',
            name='accounts_code',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
