# Generated by Django 4.2.1 on 2023-06-20 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal_accounts_api', '0003_transactionsmade_studentsfeepayments_invoicetable'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UniversityAccounts',
        ),
    ]
