# Generated by Django 4.2.1 on 2023-06-04 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FacultySchool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_code', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=40)),
                ('school_dean', models.CharField(max_length=50)),
                ('school_description', models.CharField(max_length=255)),
            ],
        ),
    ]
