# Generated by Django 4.2.1 on 2023-06-05 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_schools_api', '0002_rename_name_facultyschool_school_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultyschool',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
