# Generated by Django 4.2.1 on 2023-06-06 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portal_schools_api', '0003_facultyschool_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolFacultyDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=30)),
                ('department_code', models.CharField(max_length=40)),
                ('department_chairman', models.CharField(max_length=50)),
                ('status', models.IntegerField(default=0)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='portal_schools_api.facultyschool')),
            ],
        ),
    ]
