# Generated by Django 4.2.1 on 2023-06-06 04:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portal_school_department_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolfacultydepartment',
            name='department_description',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
