# Generated by Django 4.2.1 on 2023-06-07 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_school_department_api', '0003_alter_schoolfacultydepartment_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentActivationOtp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('otp', models.IntegerField()),
                ('is_validated', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'department_activation_otp',
            },
        ),
    ]
