# Generated by Django 4.2.1 on 2023-06-19 04:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('mathematics', 'mathematics'), ('statistics', 'statistics'), ('english', 'english'), ('IT', 'IT'), ('engineering', 'engineering')], max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='LibraryAdminActivationOtp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('otp', models.IntegerField()),
                ('is_validated', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'library_admin_activation_otp',
            },
        ),
        migrations.CreateModel(
            name='LibraryBooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=30)),
                ('Author', models.CharField(max_length=30)),
                ('Publication_Date', models.DateField()),
                ('ISBN', models.CharField(max_length=50)),
                ('Description', models.TextField()),
                ('Publisher', models.CharField(max_length=60)),
                ('Language', models.CharField(max_length=60)),
                ('Cover_Image', models.ImageField(upload_to='')),
                ('Number_of_Pages', models.CharField(max_length=60)),
                ('Availability', models.IntegerField(default=0)),
                ('Location', models.CharField(max_length=60)),
                ('Borrower', models.CharField(max_length=60)),
                ('Due_Date', models.DateField()),
                ('book_category', models.CharField(max_length=100)),
                ('Genre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal_library_api.genre')),
            ],
        ),
        migrations.CreateModel(
            name='LibraryAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('id_number', models.CharField(max_length=12)),
                ('mobile_number', models.CharField(max_length=15)),
                ('school_id_number', models.CharField(max_length=15)),
                ('status', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'lbrary_admins',
                'db_table': 'library_admin',
            },
        ),
    ]
