# Generated by Django 4.2.1 on 2023-06-19 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal_library_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='librarybooks',
            options={'ordering': ['-id'], 'verbose_name': 'library_books', 'verbose_name_plural': 'library_books'},
        ),
        migrations.AlterModelTable(
            name='librarybooks',
            table='library_books',
        ),
    ]
