# Generated by Django 4.2.1 on 2023-06-19 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_library_api', '0002_alter_librarybooks_options_alter_librarybooks_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='librarybooks',
            name='book_category',
        ),
        migrations.AddField(
            model_name='librarybooks',
            name='Borrow_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(choices=[('mathematics', 'mathematics'), ('statistics', 'statistics'), ('english', 'english'), ('it', 'it'), ('engineering', 'engineering')], max_length=50),
        ),
        migrations.AlterField(
            model_name='librarybooks',
            name='Borrower',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='librarybooks',
            name='Due_Date',
            field=models.DateField(null=True),
        ),
    ]
