# Generated by Django 4.2.1 on 2023-06-17 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_library_api', '0002_libraryadminactivationotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='libraryadmin',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
