# Generated by Django 4.2.1 on 2023-06-18 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_library_api', '0003_libraryadmin_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryBooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=30)),
                ('book_category', models.CharField(max_length=100)),
            ],
        ),
    ]
