# Generated by Django 4.2.1 on 2023-06-19 05:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portal_library_api', '0003_remove_librarybooks_book_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='librarybooks',
            name='Borrower',
            field=models.ForeignKey(max_length=60, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
