# Generated by Django 4.2.1 on 2023-06-20 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal_library_api', '0005_transactionsmade_studentsfeepayments_invoicetable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentsfeepayments',
            name='student',
        ),
        migrations.RemoveField(
            model_name='transactionsmade',
            name='transacting_user',
        ),
        migrations.DeleteModel(
            name='InvoiceTable',
        ),
        migrations.DeleteModel(
            name='StudentsFeePayments',
        ),
        migrations.DeleteModel(
            name='TransactionsMade',
        ),
    ]
