# Generated by Django 4.2.1 on 2023-06-02 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal_authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date_of_birth',
        ),
    ]
