# Generated by Django 4.2.1 on 2023-06-02 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal_authentication', '0002_remove_user_date_of_birth'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
