# Generated by Django 4.2.1 on 2023-06-03 06:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portal_authentication', '0005_loginotp_alter_roles_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginotp',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
    ]
