# Generated by Django 4.2.1 on 2023-06-29 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_authentication', '0007_passwordresetotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roles',
            name='short_name',
            field=models.CharField(choices=[('admin', 'admin'), ('accounts', 'accounts'), ('students', 'students'), ('schools', 'schools'), ('library', 'library'), ('it_admin', 'it_admin')], default='', max_length=20, unique=True),
        ),
    ]
