# Generated by Django 4.1.7 on 2023-07-05 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal_authentication', '0008_alter_roles_short_name'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='roles',
            table='roles',
        ),
    ]
