# Generated by Django 4.2.1 on 2023-06-29 04:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryAdminActivationOtp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('otp', models.IntegerField()),
                ('is_validated', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'it_admin_activation_otp',
            },
        ),
        migrations.CreateModel(
            name='ITAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.CharField(max_length=15)),
                ('full_name', models.CharField(max_length=30)),
                ('school_id_number', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('status', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'it_admin',
            },
        ),
    ]
