# Generated by Django 4.2.1 on 2023-06-29 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal_it', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LibraryAdminActivationOtp',
            new_name='ITAdminActivationOtp',
        ),
    ]
