# Generated by Django 4.1.7 on 2023-07-05 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_it', '0002_rename_libraryadminactivationotp_itadminactivationotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itadmin',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
